#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l walltime=10:00:00
#PBS -l vmem=20gb

set -e
set -x

# Make output directories
mkdir -p out_figs
mkdir -p out_dir_report

# export SUBJECTS_DIR="$(dirname "$out_dir")"

# singularity exec -e docker://brainlifemeeg/mne-freesurfer:1.12.1-7.4.1 python3 main.py

singularity  exec --env FS_LICENSE=${FS_LICENSE} -e docker://brainlifemeeg/mne-freesurfer:1.12.1-7.4.1 python3 main.py

# singularity exec -e docker://brainlifemeeg/mne-freesurfer:1.12.1-7.4.1 mne watershed_bem
